main: cx.ajneb97.Codex
version: 1.16.1
name: Codex
api-version: 1.21
author: Ajneb97
softdepend: [WorldGuard,WorldEdit,PlaceholderAPI,MythicMobs]

commands:
  zone:
    description: Main command of Codex